### ISSUE TITLE
상품 등록 시 오류 메시지가 나타나지만 상품은 등록됨

### ISSUE THREAD

**Issue by nohheeyeon** [ShopSpringBoot/Spring-Shop#25]
상품 정보를 입력하고 저장 버튼을 누를 때 "상품 등록 중 에러가 발생하였습니다."라는 오류 메시지가 나타납니다. 
그러나 상품 관리 페이지에서 확인해보면, 상품은 실제로 등록되어 있습니다.

**Comment by nohheeyeon** [comment]
* 현재 프로젝트의 이미지 파일 경로 설정이 절대경로(C:/shop/item)로 되어 있어 발생했던 현상입니다.
* 다양한 환경에서의 유지 관리에 제약이 있을 것이라고 생각되어 이를 개선하기 위해 이미지 저장 경로를 상대경로로 변경하고자 합니다.

**Comment by ljt528** [comment]
#25 해결했습니다.
