### ISSUE TITLE
상품 상세 페이지 접근 시 내부 서버 오류 발생

### ISSUE THREAD

**Issue by nohheeyeon** [ShopSpringBoot/Spring-Shop#27]
* 새로운 상품을 등록한 후 해당 상품의 상세 페이지에 접근하려고 할 때 내부 서버 오류가 발생합니다

**Comment by nohheeyeon** [comment]
* itemDtl.html의 버튼 태그를 제거했을 때 상품 상세 페이지가 정상적으로 작동했습니다
* 'order()' 함수 내부에 로직 오류가 있었던 걸로 예상됩니다

**Comment by ljt528** [comment]
#27 해결했습니다.
